version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always
    container_name: mysql_db
    volumes:
      - db_data:/home/adae/Документы/Code/Tododa/db-data/

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile-phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: RABBIT.inhole20!

volumes:
  db_data:
    driver: local
