version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    restart: always
    container_name: mysql_db
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile_phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "7000:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: RABBIT.inhole20!

volumes:
  db_data:
    driver: local
